---
# tasks file for phoebus_services_aa

# download build and install dependencies
- name: Install dependencies
  ansible.builtin.include_tasks: dependencies.yml
- name: Configure MySQL
  ansible.builtin.include_tasks: configure_mysql.yml

# configure SSL certificates if enabled
- name: Configure SSL certificates
  ansible.builtin.include_tasks: configure_ssl.yml
  when: aa_enable_ssl | bool

# build aa
# TODO: replace with the use of prebuilt binaries
- name: Build Archiver Appliance
  ansible.builtin.include_tasks: build_aa.yml

# install and deploy aa
- name: Install Archiver Appliance
  ansible.builtin.include_tasks: install_aa.yml
