---
- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Elasticsearch service
  become: true
  ansible.builtin.systemd:
    name: "{{ phoebus_services_elasticsearch_service_name }}"
    state: restarted
