---
phoebus_services_save_restore_root: /opt/epics-tools/services/save_restore
phoebus_services_save_restore_account: csstudio

phoebus_services_save_restore_http_port: 23180
phoebus_services_save_restore_https_port: 23181

phoebus_services_save_restore_version: "4.7.4"
phoebus_services_save_restore_jar: "{{ phoebus_services_save_restore_root }}/service-save-and-restore-{{ phoebus_services_save_restore_version }}.jar"
phoebus_services_save_restore_service_name: phoebus_services_save_restore

phoebus_services_save_restore_java_home: /opt/epics-tools/lib/jvm/jdk-21

# Source build artifact path from phoebus_tools role checkout/build.
phoebus_services_save_restore_source_target_dir: /opt/epics-tools/tools/phoebus/lib/phoebus/services/save-and-restore/target
phoebus_services_save_restore_source_pattern: "service-save-and-restore-{{ phoebus_services_save_restore_version }}*.jar"

# elastic info
phoebus_services_save_restore_es_host: localhost
phoebus_services_save_restore_es_port: 9200

# procServ port
phoebus_services_save_restore_procserv_port: 23146
