---
phoebus_services_phoebus_olog_webclient_olog_url: http://localhost:4181/Olog
phoebus_services_phoebus_olog_webclient_root: /opt/epics-tools/services/olog_webclient
phoebus_services_phoebus_olog_webclient_project_path: "{{ phoebus_services_phoebus_olog_webclient_root }}/phoebus-olog-web-client"
phoebus_services_phoebus_olog_webclient_version: v2.2.1
phoebus_services_phoebus_olog_webclient_account: csstudio
phoebus_services_phoebus_olog_webclient_service_name: phoebus_services_phoebus_olog_webclient

# procServ port
phoebus_services_phoebus_olog_webclient_procserv_port: 4147
